version: '3.8'

services:
  app:
    build: .
    container_name: cakephp-app
    ports:
      - 8765:80
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: cakephp-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: link_app
      MYSQL_USER: cakephp
      MYSQL_PASSWORD: cakephp
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
